name: chat_bot
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.1
  dart_openai: ^3.0.0
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_dart: ^1.0.11
  flutter:
    sdk: flutter
  provider: ^6.0.5
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
